mysql:
  host: greta-p2-g5.westeurope.cloudapp.azure.com
  user: root
  password: greta2023
  driver: mysql
  database: testEG

mysql2:
  host: localhost
  user: root
  password: root
  driver: mysql
  database: bdd_test


PG:
  host: greta-p2-g0.westeurope.cloudapp.azure.com
  user: postgres
  password: greta2023
  database: test
  driver: postgresql+psycopg2

PG-datalab:
  host: 127.0.0.1
  user: user
  password: (celui déjà fourni) 
  database: user
  driver: postgresql+psycopg2

mysql-datalab:
  host: 127.0.0.1
  user: gurgoglione
  password: f946c9aa6f3385c666a4f527a2b8ec667b5669792af488ae9e83a312c6f7b053
  database: p2ia_gurgoglione
  driver: mysql