ALTER TABLE base_maud.names MODIFY COLUMN birthYear INT NULL; 
ALTER TABLE base_maud.names MODIFY COLUMN deathYear INT NULL;
ALTER TABLE base_maud.names MODIFY COLUMN nconst VARCHAR(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.names MODIFY COLUMN primaryName varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.names MODIFY COLUMN primaryProfession varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.names MODIFY COLUMN knownForTitles varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_akas MODIFY COLUMN titleId varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_akas MODIFY COLUMN title varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_akas MODIFY COLUMN region varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_akas MODIFY COLUMN `language` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_akas MODIFY COLUMN types varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_akas MODIFY COLUMN `attributes` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_basics MODIFY COLUMN tconst varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_basics MODIFY COLUMN titleType varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_basics MODIFY COLUMN primaryTitle varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_basics MODIFY COLUMN originalTitle varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_basics MODIFY COLUMN endYear INT NULL;
ALTER TABLE base_maud.title_basics MODIFY COLUMN runtimeMinutes INT NULL;
ALTER TABLE base_maud.title_basics MODIFY COLUMN genres varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_crew MODIFY COLUMN tconst varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_crew MODIFY COLUMN directors varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_crew MODIFY COLUMN writers varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_episode MODIFY COLUMN tconst varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_episode MODIFY COLUMN parentTconst varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_episode MODIFY COLUMN seasonNumber INT NULL;
ALTER TABLE base_maud.title_episode MODIFY COLUMN episodeNumber INT NULL;
ALTER TABLE base_maud.title_principals MODIFY COLUMN tconst varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_principals MODIFY COLUMN nconst varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_principals MODIFY COLUMN category varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_principals MODIFY COLUMN job varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_principals MODIFY COLUMN `characters` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_ratings MODIFY COLUMN tconst varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE base_maud.title_ratings MODIFY COLUMN averageRating INT NULL;
