ALTER TABLE bdd_all_test.names MODIFY COLUMN birthYear INT NULL; 
ALTER TABLE bdd_all_test.names MODIFY COLUMN deathYear INT NULL;
ALTER TABLE bdd_all_test.names MODIFY COLUMN nconst VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.names MODIFY COLUMN primaryName varchar(105) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.names MODIFY COLUMN primaryProfession varchar(66) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.names MODIFY COLUMN knownForTitles varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_akas MODIFY COLUMN titleId varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_akas MODIFY COLUMN title varchar(656) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_akas MODIFY COLUMN region varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_akas MODIFY COLUMN `language` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_akas MODIFY COLUMN types varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_akas MODIFY COLUMN `attributes` varchar(62) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_basics MODIFY COLUMN tconst varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_basics MODIFY COLUMN titleType varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_basics MODIFY COLUMN primaryTitle varchar(421) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_basics MODIFY COLUMN originalTitle varchar(421) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_basics MODIFY COLUMN endYear INT NULL;
ALTER TABLE bdd_all_test.title_basics MODIFY COLUMN runtimeMinutes INT NULL;
ALTER TABLE bdd_all_test.title_basics MODIFY COLUMN genres varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_crew MODIFY COLUMN tconst varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_crew MODIFY COLUMN directors varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_crew MODIFY COLUMN writers varchar(13500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_episode MODIFY COLUMN tconst varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_episode MODIFY COLUMN parentTconst varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_episode MODIFY COLUMN seasonNumber INT NULL;
ALTER TABLE bdd_all_test.title_episode MODIFY COLUMN episodeNumber INT NULL;
ALTER TABLE bdd_all_test.title_principals MODIFY COLUMN tconst varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_principals MODIFY COLUMN nconst varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_principals MODIFY COLUMN category varchar(19) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_principals MODIFY COLUMN job varchar(290) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_principals MODIFY COLUMN `characters` varchar(1308) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_ratings MODIFY COLUMN tconst varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL;
ALTER TABLE bdd_all_test.title_ratings MODIFY COLUMN averageRating INT NULL;
